.gitignore
client/README.md
client/package.json
client/public/index.html
client/public/manifest.json
client/public/robots.txt
client/src/App.css
client/src/App.js
client/src/index.css
client/src/index.js
package-lock.json

[Client / Server] / #01 / 배포 client 세팅

---

server/app.js
server/package-lock.json
server/package.json

[Server] / #02 / server 배포 세팅

---

server/app.js
server/package-lock.json
server/package.json

[Server]  / #6 / app.js cors 적용

---

client/src/styled/styleMain.js

styleMain.js : font-size 반응형으로 변경

[Client] / #10 / styleMain.js : font-size 반응형으로 변경

---

client/src/component/nav.js

[Client] / #12 / merge 오류 수정

---

client/package.json
client/src/component/nav.js
client/src/styled/styleMain.js
client/src/styled/styleNav.js

[Client] / #13 / dev에서 merge 안된 부분 수정

---

client/src/component/nav.js
client/src/styled/styleMain.js
client/src/styled/styleNav.js

- nav 햄버거 버튼 및 animation 구현
- nav scroll에 따른 배경색 변경 css 수정

[Client] / #14 / nav 햄버거 버튼 및 animation 구현

---

client/src/styled/styleNav.js

styleNav.js : css merge 안 된 부분 재수정

[Client] / #15 / styleNav.js : css merge 안 된 부분 재수정

---

client/src/component/nav.js
client/src/styled/styleMain.js
client/src/styled/styleNav.js

- main 반응형 css 수정
- nav바 변경되는 break point 재설정

[Client] / #16 / main 반응형 css 수정

---

server/migrations/20211023054257-create-chef.js
server/migrations/20211023143446-create-foreign-keys.js
server/models/chef.js
server/models/reservation.js
server/seeders/20211102014301-dummyUsers.js
server/seeders/20211102020720-dummyChefs.js
server/seeders/20211102053107-dummyCourses.js
server/seeders/20211102060437-dummyReservations.js
server/seeders/20211102062052-dummyReviews.js

[Server] / #21 / dummydata 만들어주기

---

server/controllers/user/login.js

[Server] / #22 / accessToken 스펠링 수정

---

client/package.json
client/src/App.css
client/src/styled/styleNav.js

- nav 로고 폰트 크기 수정 및 media query 적용

[Client] / #19 / nav 로고 폰트 크기 수정 및 media query 적용

---

client/package.json
server/controllers/user/signup.js

package.json install 및 database에 회원가입 추가

[Client / Server] / #05 / package.json install 및 database에 회원가입 추가

---

client/src/component/login.js
client/src/component/signup.js
server/controllers/user/login.js
server/controllers/user/signup.js

[Client / Server] / #07 / axios 회원가입 로그인 연결

---

server/package-lock.json

sequelize dependency version upgrade

[Server] / #22 / sequelize dependency version upgrade

---

client/src/component/login.js
server/controllers/user/login.js

[Client] / #21 / try catch 확인

---

client/src/component/login.js
client/src/component/nav.js
client/src/features/user/user.js
client/src/styled/styleNav.js

- accessToken 저장 빠져있던 부분 수정 
- 아직 axios 처리는 구현하지 못했으나 redux에서 로그아웃(=저장했던 유저 정보 날리기) 구현
- nav 반응형 css 수정

[Client] / #23 / Feature/login or signup

---

client/src/component/login.js
client/src/component/signup.js
client/src/modal/signupModal.js
client/src/pages/loginOrSignup.js
client/src/styled/styledModal.js

[Client] / #25 / login, signup modal 완성

---

server/controllers/user/index.js
server/controllers/user/logout.js
server/routes/user.js

[Server] / #26 / logout 구현

---

client/src/App.js
client/src/component/nav.js
client/src/modal/logoutModal.js
client/src/styled/styledModal.js

[Client] / #26 / 로그아웃 모달 완성 및 axios 요청 완료

---

client/src/styled/styleNav.js

[Client] / #28 / nav bar 구현 수정

---

client/src/component/nav.js
client/src/component/signup.js
client/src/modal/logoutModal.js
client/src/styled/styledModal.js

[Client] / #29 / signup 이중 삼항식 수정

---

client/src/styled/styleMain.js

[Client] / #34 / mainpage 반응형

---

client/src/component/chefAllCourse.js
client/src/component/chefAllInfo.js
client/src/component/chefAllReview.js
client/src/pages/chefInfo.js
client/src/styled/styleChefInfo.js

- chefInfo html 태그 및 반응형 css 기본 구조 작성

[Client] / #35 / chefInfo html 태그 및 반응형 css 기본 구조 작성

---

client/src/component/mainSection3.js
client/src/styled/styleFindChef.js
client/src/styled/styleMain.js
server/seeders/20211102014301-dummyUsers.js
server/seeders/20211102020720-dummyChefs.js

[Client] / #36 / mainPage 반응형 완성

---

client/src/component/mainSection4.js
client/src/styled/styleMain.js
server/seeders/20211102014301-dummyUsers.js
server/seeders/20211102020720-dummyChefs.js

[Sever] / #27 / seed 수정중

---

client/src/component/chefInfoCourse.js
client/src/component/chefInfoInfo.js
client/src/component/chefInfoReview.js
client/src/component/nav.js
client/src/component/reservationDate.js
client/src/component/reservationDone.js
client/src/component/reservationInfo.js
client/src/component/reservationNotice.js
client/src/component/reservationPayment.js
client/src/modal/pictureModal.js
client/src/pages/chefInfo.js
client/src/pages/findChef.js
client/src/pages/reservation.js
client/src/styled/styleChefInfo.js
client/src/styled/styleFindChef.js
client/src/styled/styleNav.js
client/src/styled/styleReservation.js
client/src/styled/styledModal.js

- 반응형 nav, chefInfo css 수정 
- styledComponent 태그 정리
- chefInfo의 review부분에서 작은 사진 아이콘을 클릭했을 때 보일 사진 모달 기본 작업

[Client] / #38 / 반응형 nav, chefInfo css 수정 및 클릭했을 때 보일 사진 모달 기본 작업

---

server/controllers/chef/chefId.js

[Server] / #29 / chefInfo 상세페이지 서버 완료

---

client/src/App.js
client/src/component/chefInfoCourse.js
client/src/component/chefInfoInfo.js
client/src/component/chefInfoReview.js
client/src/features/user/user.js
client/src/pages/chefInfo.js
client/src/pages/findChef.js
client/src/styled/styleChefInfo.js
client/src/styled/styleFindChef.js
server/controllers/chef/chefId.js
server/controllers/chef/cuisine.js

- findChef 페이지 관련 css 수정
- 셰프 정보 요청하는 axios 작업
- select값이 변경 될 떄 마다 axios 요청 가도록 작업

[Client] / #38 / findChef 페이지 관련 css 수정과 axios 작업

---

server/config/config.js

[Server] / #31 / confing.js 수정

---

scripts/start.sh

[Server] / #32 / start.sh 임시수정

---

scripts/start.sh

[Server] / #33 / start.sh 재수정

---

server/check.js

[Server] / #34 / 임시파일 생성

---

server/models/index.js

config.js port 확인차 models config 변경

[Server] / #35 / config.js port 확인차 models config 변경

---

server/models/index.js

[Server] / #36 / index.js port 삭제

---

client/src/App.js
client/src/pages/reservation.js
client/src/styled/styleReservation.js

[Client] / #39 / app.js 리다이렉트

---

server/migrations/20211023054257-create-chef.js
server/migrations/20211023054312-create-review.js
server/models/chef.js
server/models/review.js
server/seeders/20211102020720-dummyChefs.js
server/seeders/20211102062052-dummyReviews.js

migrate rating int -> string로 변경

[Server] / #37 / migrate rating int -> string로 변경

---

client/package.json
client/src/App.js
client/src/component/chefInfoCourse.js
client/src/component/chefInfoInfo.js
client/src/component/reservationDate.js
client/src/component/reservationDone.js
client/src/component/reservationInfo.js
client/src/component/reservationNotice.js
client/src/component/reservationPayment.js
client/src/pages/findChef.js
client/src/pages/reservation.js
client/src/styled/styleReservation.js
server/check.js
server/config/config.js

[Client] / #40 / findchef pagenation 재적용

---

server/controllers/user/login.js

Token 으로 인한 pending 상태 의심으로 주석처리 시험

[Server] / #39 / Token 으로 인한 pending 상태 의심으로 주석처리 시험

---

server/controllers/user/login.js

Token 으로 인한 pending 상태 의심으로 주석처리 재시험

[Server] / #39 / Token 으로 인한 pending 상태 의심으로 주석처리 재시험

---

server/controllers/user/login.js

accessToken 으로 인한 pending 상태 의심으로 재시험

[Server] / #40 / accessToken 으로 인한 pending 상태 의심으로 재시험

---

scripts/start.sh
server/controllers/user/login.js

accessToken으로 인한 start.sh 파인 재수정

[Server] / #41 / accessToken으로 인한 start.sh 파인 재수정

---

server/controllers/chef/chefId.js

[Server] branch main pull -> chef review 세분화하기

---

server/controllers/chef/chefId.js

chef review 갯수 startNum과 endNum의 숫자에 따라 slice 하기 구현

[Server] / #43 / chef review 갯수 startNum과 endNum의 숫자에 따라 slice 하기 구현

---

client/package.json
client/src/component/reservationDate.js
client/src/component/reservationInfo.js
client/src/modal/addressModal.js
client/src/pages/reservation.js
client/src/styled/styleReservation.js
client/src/styled/styledModal.js

- 변경사항에 따른 form 태그 수정
- react-hook-form을 활용한 form 작성
- react-hook-form을 활용하여 입력사항에 대한 에러 작성
- 에러 관련 코드부분 보완 작업 중 
- 다음 주소 검색 API(react-daum-postcode)를 활용하여 주소 검색 구현
- 주소 검색을 위한 모달 제작 및 css 적용

[Client] / #42 / reservation 기능 구현 및 주소 검색

---

client/src/component/chefInfoReview.js
client/src/component/nav.js
client/src/component/reservationDate.js
client/src/component/signup.js
client/src/pages/chefInfo.js
client/src/pages/findChef.js
client/src/styled/styleNav.js

- nav 반응형 수정
- signup form에 비밀번호 확인 Input창 추가 및 유효성검사 적용
- chefInfof에 axios 요청 수정 및 pagenation 적용
- reservation에서 핸드폰 번호 관련 유효성 검사 추가

[Client] / #43 / chefInfo, reservation, nav, signup 수정

---

server/app.js
server/controllers/chef/chefId.js
server/controllers/index.js
server/controllers/reservation/index.js
server/controllers/reservation/reservation.js
server/controllers/user/kakao.js
server/routes/reservation.js

[Server] / #43 / reservation 경로 구현

---

client/src/component/chefInfoCourse.js
client/src/component/reservationDate.js
client/src/component/reservationInfo.js
client/src/component/reservationNotice.js
client/src/component/reservationPayment.js
client/src/modal/addressModal.js
client/src/pages/chefInfo.js
client/src/pages/reservation.js
client/src/styled/styleReservation.js
server/controllers/chef/chefId.js

- reservation에서 다음 주소 검색 API 사용부분은 react-hook-form과 별개로 사용하도록 수정
- react-hook-form과 사용은 가능하나, 주소를 검색해서 값이 변경이 되도 에러 메세지가 사라지지 않는 오류가 있었음
- 현재 위와 같은 오류는 없어졌지만,  주소 관련 에러 메세지가 조금 어색해보임 (수정 예정)
- react-hook-form과 주소값을 따로 관리하고 있어서, 바로 onSubmit에서 hook-form으로 부터 받아온 데이터를 처리할 수는 없음
- 모든 데이터를 합친 후에 reservationPayment가 전달받는 식으로 작성함
- 핸드폰 번호 유효성 검사 추가
- payment에서 axios할 수 있도록 받아온 데이터 확인 및 기본적인 axios 코드 작성 
- 주말에 admin관련 routing과 구조 작업 진행 예정

[Client] / #44 / reservation form 관련 수정

---

server/controllers/reservation/reservation.js

reservation token 만료와 만료되지 않았을 때로 구분해서 post 요청 구현

[Server] / #44 / reservation token 만료와 만료되지 않았을 때로 구분해서 post 요청 구현

---

client/src/App.js
client/src/app/store.js
client/src/component/adminpageBechef.js
client/src/component/adminpageChef.js
client/src/component/adminpageReview.js
client/src/component/login.js
client/src/component/nav.js
client/src/component/signup.js
client/src/features/user/modal.js
client/src/modal/loginErrorModal.js
client/src/modal/loginModal.js
client/src/modal/logoutModal.js
client/src/modal/signupModal.js
client/src/pages/adminpage.js
client/src/pages/loginOrSignup.js
client/src/styled/styleAdminpage.js

- admin페이지 기본 세팅 (현재 /admin으로 들어가면 볼 수 있음)
- login, signup 관련 redux 작업
- login, signup 확인해보니 modal관련 사항이 많아지는 것 같아 client/features/user에 modal 상태를 관리하는 파일 생성함
- signup 때 중복 닉네임이여도 회원가입이 되는데, 이렇게 작동하는게 맞는지 확인 필요

[Client] / #45 / admin 기본 세팅 및 modal 관련 redux 작업

---

server/migrations/20211121120108-create-bechef.js
server/migrations/20211121121326-create-foreign-keys.js
server/models/bechef.js
server/seeders/20211102014301-dummyUsers.js
server/seeders/20211122013830-dummyBechef.js

[Server] / #46 / migrate/seed 완성

---

server/app.js
server/controllers/admin/index.js
server/controllers/admin/review.js
server/controllers/index.js
server/routes/admin.js

[Server] / #47 / admin review get 요청 구현 완료

---

server/controllers/admin/review.js
server/routes/admin.js

[Server] / #48 / admin review params 추가

---

client/src/component/adminpageBechef.js
client/src/component/adminpageChef.js
client/src/component/adminpageReview.js
client/src/component/login.js
client/src/component/nav.js
client/src/features/user/modal.js
client/src/features/user/user.js
client/src/modal/reservDeclinedModal.js
client/src/pages/adminpage.js
client/src/pages/loginOrSignup.js
client/src/pages/reservation.js
client/src/styled/styleAdminpage.js
client/src/styled/styleFindChef.js

- nav에 유저 사진 보이도록 수정
- admin 페이지 접근 권한 수정 (지금은 nickname이 김코딩이면 접근 가능)
- admin review부분 기본 작업 및 css 적용
- admin review axios, pagenation 구현
- reservation에서 로그인 상태 판별하여 로그인 전이라면 findchef로 리다이렉트

[Client] / #46 / admin, reservation, nav 관련 작업

---

server/controllers/admin/chef.js
server/controllers/admin/index.js
server/controllers/admin/review.js
server/routes/admin.js

[Server] / #49 / adminPage 리뷰/셰프 조회 및 삭제 구현 완료

---

client/src/styled/styleAdminpage.js

[Client] / #47 / admin review select css 수정

---

client/src/component/adminpageBechef.js
client/src/component/adminpageChef.js
client/src/component/adminpageReview.js
client/src/styled/styleAdminpage.js
server/controllers/admin/chef.js
server/controllers/admin/review.js
server/routes/admin.js

- admin의 bechef페이지 관련 기본 html, css 작업
- admin의 chef페이지 관련 기본 html, css 작업

[Client] / #48 / admin페이지에서 bechef, chef 컴포넌트 기본 작업

---

client/src/component/adminpageBechef.js
client/src/component/adminpageChef.js
client/src/component/login.js
client/src/component/nav.js
client/src/features/user/user.js
client/src/pages/adminpage.js
client/src/pages/beChef.js
client/src/styled/styleAdminpage.js
client/src/styled/styleBeChef.js
server/controllers/user/signup.js
server/models/user.js

- admin페이지 css 수정 및 redux user 기초 상태값 수정

[Client] / #49 / admin페이지 css 수정 및 redux user 기초 상태값 수정

---

client/src/pages/beChef.js
client/src/styled/styleBeChef.js

[Client] / #50 / beChef 관련 css 및 에러메세지 작업

---

server/controllers/admin/bechef.js
server/controllers/admin/index.js
server/controllers/chef/pdfFile.js
server/models/bechef.js
server/routes/admin.js

[Server] / #50 / 날짜 계산하기 구현

---

client/src/component/reservationDone.js
client/src/component/reservationPayment.js
client/src/styled/styleReservation.js
server/controllers/reservation/reservation.js

- reservation axios 작업
- reservation 완료창 작업

[Client] / #51 / reservation axios, css 작업

---

server/controllers/chef/pdfFile.js
server/controllers/user/google.js
server/controllers/user/kakao.js
server/migrations/20211121121326-create-foreign-keys.js
server/models/bechef.js

[Server] / #51 / bechefs models 오류 수정 및 추가 작업

---

server/controllers/admin/bechef.js
server/controllers/user/google.js

adminPage 시간 filter 구현 및 구글 소셜 로그인 시 에러 발생 수정

[Server] / #52 / adminPage 시간 filter 구현 및 구글 소셜 로그인 시 에러 발생 수정

---

server/controllers/admin/bechef.js
server/controllers/admin/chef.js
server/controllers/admin/review.js
server/controllers/chef/pdfFile.js

adminpage accessToken 및 refreshToken 유효성 검사 전체 추가

[Server] / #53 / adminpage accessToken 및 refreshToken 유효성 검사 전체 추가

---

client/src/App.js
client/src/component/adminpageBechef.js
client/src/component/adminpageChef.js
client/src/component/adminpageReview.js
client/src/component/reservationPayment.js
client/src/features/user/user.js
client/src/pages/beChef.js
client/src/pages/findChef.js
client/src/styled/styleAdminpage.js
client/src/styled/styleReservation.js

[Client] / #52 / reservation axios 작업 수정

---

package-lock.json
server/controllers/admin/bechef.js
server/controllers/admin/bechefConfirm.js
server/controllers/admin/bechefRefuse.js
server/controllers/admin/index.js
server/controllers/sendMail.js
server/package-lock.json
server/package.json
server/routes/admin.js

admin page bechef 수락 및 거절 구현 / nodemailer 활용

[Server] admin page bechef 수락 및 거절 구현 / nodemailer 활용

---

server/controllers/admin/bechef.js

[Server] / #55 / admin bechef nickname 추가

---

server/app.js
server/controllers/admin/chef.js
server/controllers/index.js
server/controllers/mypage/checkReservation.js
server/controllers/mypage/index.js
server/controllers/reservation/reservation.js
server/migrations/20211023054312-create-review.js
server/models/review.js
server/routes/mypage.js
server/seeders/20211102060437-dummyReservations.js
server/seeders/20211102062052-dummyReviews.js

mypage 예약 확인 및 취소, review table 수정

[Server] / #56 / mypage 예약 확인 및 취소, review table 수정

---

client/src/component/adminpageBechef.js
client/src/component/mypageChefEdit.js
client/src/component/mypageEdit.js
client/src/component/mypageReservation.js
client/src/component/mypageReview.js
client/src/component/nav.js
client/src/styled/styleFindChef.js
client/src/styled/styleMypage.js

- mypage 예약 확인 페이지 기본 html, css 작업
- mypage 개인정보 변경 페이지 기본 html, css 작업
- mypage 리뷰 작성 페이지 기본 html, css 작업

[Client] / #54 / mypage 기본 html, css 작업

---

server/controllers/mypage/checkReview.js
server/controllers/mypage/index.js
server/routes/mypage.js

[Server] / #57 / mypage review 기본 세팅 완료

---

server/controllers/mypage/checkReview.js
server/controllers/mypage/index.js
server/controllers/mypage/userInfo.js
server/routes/mypage.js

mypage review 및 userInfo 페이지 서버 구현 완료

[Server] / #58 / mypage review 및 userInfo 페이지 서버 구현 완료

---

client/src/component/mypageChefEdit.js
client/src/component/mypageEdit.js
client/src/component/mypageReservation.js
client/src/features/reservation/reservation.js
client/src/styled/styleMypage.js

- mypage edit css 기본작업 완료
- mypage chefEdit 기본 html, css 작업
- mypage reservation 달력 구현

[Client] / #55 / mypage 기초 틀 작업 및 달력 관련 작업

---

client/src/component/mypageReview.js
server/routes/chef.js
server/routes/mypage.js

[Client / Server] / #11 / 사진 여러장 업로드 multer 작업

---

client/src/app/store.js
client/src/component/mypageChefEdit.js
client/src/component/mypageEdit.js
client/src/component/nav.js
client/src/features/chef/chef.js
client/src/styled/styleMypage.js
client/src/styled/styleNav.js

- mypage Edit 반응형 구현 및 chef 관련 redux 수정
- mypage chefEdit 반응형 구현
- mypage 글자 색 변경

[Client] / #56 / mypage 반응형 구현 및 chef 관련 redux 수정

---

client/src/component/mypageChefEdit.js
client/src/component/mypageEdit.js
client/src/component/mypageReservation.js
client/src/component/mypageReview.js
client/src/features/reservation/reservation.js
client/src/styled/styleMypage.js
server/controllers/mypage/checkReservation.js

[Client] / #57 / mypage review 반응형 구현

---

client/src/component/mypageReservation.js
client/src/features/reservation/reservation.js
client/src/features/user/modal.js
client/src/modal/deleteReservModal.js
client/src/pages/mypage.js
client/src/styled/styleMypage.js

- mypage reservation axios, redux 작업중

[Client] / #58 / mypage reservation axios, redux 작업중

---

client/src/component/mypageChefEdit.js
client/src/component/mypageEdit.js
client/src/component/mypageReview.js
server/controllers/mypage/arrayImg.js
server/controllers/mypage/chefInfo.js
server/controllers/mypage/image.js
server/controllers/mypage/index.js
server/routes/mypage.js

mypage 서버 작업 완료 및 이미지 multer 구현 완료

[Client / Server] / #12 / mypage 서버 작업 완료 및 이미지 multer 구현 완료

---

client/src/component/mypageReservation.js
client/src/features/reservation/reservation.js
client/src/modal/deleteReservModal.js

-  mypage user reservation 구현
- invalid date value 오류 수정중
- 예약날짜가 오늘로부터 1주일 이내로 남은 경우 취소 불가 버튼 보임

[Client] / #59 / mypage 예약 확인 페이지 구현

---

server/controllers/mypage/checkReservation.js

mypage user reservation corse 이름 추가

[Server] / #60 / mypage user reservation corse 이름 추가

---

client/src/component/adminpageBechef.js
client/src/component/adminpageChef.js
client/src/component/adminpageReview.js
client/src/component/chefInfoReview.js
client/src/component/login.js
client/src/component/mypageReservation.js
client/src/features/user/modal.js
client/src/modal/adminOrChefWarningModal.js
client/src/pages/findChef.js
client/src/pages/reservation.js
server/controllers/admin/bechef.js
server/controllers/admin/chef.js
server/controllers/admin/review.js
server/controllers/chef/chefId.js
server/controllers/chef/cuisine.js

[Client] / #60 / pagenation 수정

---

server/controllers/user/login.js

[Server] / #61 / login 할 때 chefId 주기

---

server/app.js
server/controllers/index.js
server/controllers/mainpage/bestChef.js
server/controllers/mainpage/index.js
server/routes/mainPage.js

mainpage에서 보여질 cuisine별 best chef 구현 완료

[Server] / #62 / mainpage에서 보여질 cuisine별 best chef 구현 완료

---

client/src/component/mypageReservation.js
client/src/component/mypageReview.js
client/src/features/chef/chef.js
client/src/features/review/review.js

[Client] / #62 / mypage review axios 작업중

---

client/src/component/chefInfoReview.js
client/src/pages/findChef.js
client/src/styled/styleFindChef.js

[Client] / #64 / 별점에 따른 이미지 처리

---

server/controllers/mypage/chefInfo.js

[Server] / #63 / mypage chefInfo course 추가

---

server/controllers/user/google.js
server/controllers/user/kakao.js

소셜 로그인 했을 때 isChef Boolean 값으로 chefId 건내주기

[Server] / #64 / 소셜 로그인 했을 때 isChef Boolean 값으로 chefId 건내주기

---

client/src/component/mainSection3.js
client/src/pages/findChef.js
server/controllers/mypage/checkReview.js

[Server] / #65 / rating 평균 내기 업데이트

---

client/src/component/reservationPayment.js
client/src/modal/addressModal.js
client/src/pages/reservation.js
client/src/styled/styleReservation.js

[Client] / #66 / iamport 클라이언트 코드 작성

---

client/public/index.html
client/src/component/reservationPayment.js
server/controllers/reservation/payments.js
server/controllers/reservation/reservation.js
server/controllers/user/google.js
server/migrations/20211023054329-create-reservation.js
server/models/reservation.js
server/routes/reservation.js
server/seeders/20211102060437-dummyReservations.js

[Client / Server] / #15 / 결제완료 서버에서 조회까지 구현

---

client/src/component/mypageChefEdit.js
client/src/component/mypageEdit.js
client/src/component/mypageReservation.js
client/src/component/mypageReview.js
client/src/component/reservationDone.js
client/src/component/reservationPayment.js
client/src/component/signup.js
client/src/features/user/modal.js
client/src/modal/choiceModal.js
client/src/modal/deleteReservModal.js
client/src/modal/oneSentenceModal.js
client/src/styled/styleMypage.js
client/src/styled/styleReservation.js

- mypage edit에서 modal 수정 및 탈퇴 구현
- mypage edit에서 변경할 때 유효성검사 적용 
- 환불 및 영수증 보기 관련 클라이언트 기본 세팅

[Client] / #67 / mypage 관련 redux, axios작업 

---

client/src/component/mypageReservation.js
client/src/features/user/modal.js
client/src/modal/deleteReservModal.js
server/controllers/mypage/checkReservation.js
server/controllers/reservation/payments.js
server/migrations/20211023054329-create-reservation.js
server/models/reservation.js

[Client / Server] / #17 / 결제시스템 구현 완료

---

client/src/component/chefInfoReview.js
client/src/component/mypageChefEdit.js
client/src/component/mypageReservation.js
client/src/component/reservationDate.js
client/src/component/reservationPayment.js
client/src/pages/reservation.js
client/src/styled/styleMypage.js

-  mypage axios 수정 및 reservation 수정

[Client] / #68 / mypage axios 수정 및 reservation 수정

---

server/modules/multer.js

[Server] aws accesskey 이름 바꾸기

---

client/src/component/mypageEdit.js

[Client] / #69 / 탈퇴 처리 

---

server/modules/multer.js

[Client] 탈퇴처리

---

server/controllers/user/google.js
server/controllers/user/kakao.js

[Server] social login console.log

---

client/src/component/footer.js
client/src/component/mypageReview.js
client/src/modal/oneSentenceModal.js
client/src/pages/loginOrSignup.js
client/src/styled/styleFindChef.js
client/src/styled/styleFooter.js
client/src/styled/styleLoginOrSignup.js
client/src/styled/styleNav.js

[Client] / #70 / footer 작업

---

server/controllers/chef/chefId.js
server/controllers/mypage/chefImg.js
server/controllers/mypage/image.js
server/controllers/mypage/index.js
server/controllers/reservation/reservation.js
server/controllers/user/login.js
server/routes/mypage.js

chefImage 작업, reservationDate 작업, 조건 rating 작업

[Server] / #66 / chefImage 작업, reservationDate 작업, 조건 rating 작업

---

client/src/component/adminpageBechef.js
server/controllers/admin/bechefIsConfirm.js

[Client / Server] nodemailer 관련 수정

---

client/src/component/reservationDate.js
client/src/pages/reservation.js

- reservation date-picker 관련 수정

[Client] reservation date-picker 관련 수정

---

client/src/component/reservationPayment.js
server/controllers/admin/bechefIsConfirm.js
server/controllers/reservation/payments.js
server/controllers/sendMail.js

[Server] sendMail port 변경

---

server/controllers/reservation/reservation.js

reservation accessToken 및 refreshToken 추가

[Server] reservation accessToken 및 refreshToken 추가

---

client/src/component/chefInfoReview.js
client/src/component/login.js
client/src/component/mainSection3.js
client/src/component/mypageReservation.js
client/src/component/mypageReview.js
client/src/features/user/user.js
client/src/modal/needReLoginModal.js
client/src/modal/pictureModal.js
client/src/pages/chefInfo.js
client/src/pages/findChef.js
client/src/pages/mypage.js
client/src/pages/reservation.js
client/src/styled/styleBeChef.js
client/src/styled/styleChefInfo.js
client/src/styled/styleFindChef.js
client/src/styled/styleMain.js
server/controllers/mypage/checkReservation.js
server/controllers/token/accessToken.js
server/controllers/token/refreshToken.js

- star rating component 수정 
- mypage에서 refresh token 없는 경우 작성
- reservation에서 refresh token 없는 경우 작성

[Client] css 변경 및 star component 관련 수정

---

scripts/start.sh

[Server] scripts start.sh

---

client/src/styled/styleAdminpage.js

[Client] test

---

client/src/component/mainSection3.js
client/src/styled/styleMain.js

- main bestOfChefsWrap Link 연결 작업

[Client] / #71 / main bestOfChefsWrap Link 연결 작업

---

scripts/start.sh
server/controllers/token/refreshToken.js
server/controllers/user/kakao.js

[Server] kakao headers error 수정

---

client/src/App.js
client/src/component/mypageEdit.js
client/src/component/reservationDone.js
client/src/component/reservationInfo.js
client/src/component/reservationPayment.js
client/src/modal/addressModal.js
client/src/pages/beChef.js
client/src/pages/reservation.js
client/src/pages/reservationDonePage.js
client/src/styled/styleAdminpage.js
client/src/styled/styleChefInfo.js
client/src/styled/styleFindChef.js
client/src/styled/styleMain.js
client/src/styled/styleReservation.js
client/src/styled/styledModal.js

- css 수정 및 import 관련 m_redirect_url 지정
- m_redirect_url 지정은 했는데 아직 모바일 결제가 되는지는 확인 필요함(웹에서 모바일 결제 해보려니까 앱페이로 넘어가서 결제 어려움). 배포환경에서 시도해봐야 할듯

[Client] / #72 / css 수정 및 import 관련 m_redirect_url 지정

---

client/src/component/reservationPayment.js

[Client] / #73 / url 수정

---

client/src/component/reservationPayment.js

[Client] payment url 수정

---

client/src/component/reservationPayment.js
client/src/pages/reservationDonePage.js

- reservationDonePage axios 수정

[Client] / reservationDonePage axios 수정

---

client/src/pages/reservationDonePage.js

[Client] reservationDonePage.js 수정

---

client/src/pages/reservationDonePage.js

- reservationDonePage axios 수정

[Client] reservationDonePage axios 수정

---

client/src/pages/reservationDonePage.js

[Client] new Date 관련 수정

---

client/src/component/reservationPayment.js
client/src/pages/reservationDonePage.js

[Client] date 관련 수정

---

client/src/pages/reservationDonePage.js

[Client] date 수정

---

client/src/pages/reservationDonePage.js

[Client] js date-fns 관련 수정

---

client/src/component/mainSection3.js
client/src/component/mypageReview.js
client/src/component/reservationPayment.js
client/src/pages/findChef.js
client/src/pages/reservationDonePage.js
client/src/styled/styleMain.js

[Client] css 수정 및 console.log 찍어보기

---

client/src/pages/reservationDonePage.js

[Client] reservation date test 변경

---

client/src/component/nav.js
client/src/styled/styleAdminpage.js
client/src/styled/styleMain.js
client/src/styled/styleMypage.js
client/src/styled/styleNav.js

[Client] / #76 / css 전제적 수정

---

client/src/component/chefInfoReview.js
client/src/component/mypageReview.js
client/src/component/reservationPayment.js
client/src/modal/pictureModal.js
client/src/pages/mypage.js
client/src/styled/styleChefInfo.js
client/src/styled/styleMypage.js
client/src/styled/styledModal.js
server/controllers/mypage/arrayImg.js

- 사진 모달, chefInfo review 관련 수정 및 css 수정

[Client] / #75 / 사진 모달, chefInfo review 관련 수정 및 css 수정

---

client/src/pages/chefInfo.js
server/controllers/user/google.js

AOS Loading 상태에 따른 적용 및 구글 로그인 수정

[Client / Server] / #19 / AOS Loading 상태에 따른 적용 및 구글 로그인 수정

---

client/src/styled/styleBeChef.js

[Client] / #78 / styleBeChef input 수정

---

client/src/component/login.js
client/src/component/mypageChefEdit.js
client/src/component/mypageEdit.js
client/src/component/mypageReservation.js
client/src/component/mypageReview.js
client/src/component/reservationDate.js
client/src/component/reservationPayment.js

[Client] / #79 / warning message 지우기

---

client/public/index.html
client/src/component/reservationDate.js
client/src/component/signup.js

[Client] / #80 / react-hook-form 관련 수정

---

client/src/component/signup.js
client/src/features/chef/chef.js
client/src/modal/logoutModal.js
client/src/pages/chefInfo.js
client/src/pages/loginOrSignup.js
client/src/pages/reservation.js

[Client] / #81 / warning error 수정

---

client/src/App.js
server/controllers/user/google.js

[Server] social login redirect 수정

---

client/src/component/chefInfoInfo.js
client/src/styled/styleFindChef.js
client/src/styled/styleMypage.js

[Client] 셰프 img cover에 맞추기

---

client/src/component/adminpageBechef.js
client/src/component/adminpageLoading.js
client/src/component/chefInfoInfo.js
client/src/component/mypageChefEdit.js
client/src/pages/adminpage.js
client/src/styled/styleAdminpage.js
client/src/styled/styleMypage.js

- adminpage bechef에서 승인/거부할때 시간이 오래 걸려서 그 시간동안 보여줄 loading indicator 추가
- chefEdit페이지에서 셰프 되자마자 들어와서 cuisine 선택 관련 기본값 지정
- chefEdit페이지에서 css 수정

[Client] / #84 / css 수정

---

client/src/component/reservationPayment.js

[Client] axios url 관련 수정

---

client/src/component/reservationDate.js
client/src/pages/reservation.js

- reservation시 인원 선택 select 변경

[Client] / #86 / reservation시 인원 선택 select 변경

---

client/src/component/reservationDate.js
client/src/component/reservationPayment.js
client/src/pages/reservation.js

[Client] dev를 main으로 머지

---

client/src/component/mypageChefEdit.js

[Client] / #88 / mypage chefEdit 인원 입력 관련 수정

---

client/src/component/mainSection3.js
client/src/features/user/user.js
client/src/pages/findChef.js
server/controllers/mainpage/bestChef.js

- Server에서 findBestHansikChef만 String으로 조건이 감싸져있지 않아서 그부분 수정
- mainSection3, findChef에서 점수 소수점까지 보이도록 수정

[Client / Server] 셰프 평점 관련 수정
